name: Test - End to End

on:
  pull_request:
  push:
    branches: [ 'develop', 'release' ]
  schedule:
    - cron: '30 3 * * 1-5'
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        config: [desktop, mobile]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn
          yarn global add wait-on
      - name: Start preview server
        run: yarn start:test &
      - name: Run tests
        run: wait-on -v -t 60000 -c ./scripts/waitOnConfig.js http-get://localhost:8080 && yarn codecept:${{ matrix.config }}
        env:
          TEST_RETRY_COUNT: 2
          WORKER_COUNT: 2
      - name: Uploading artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{ matrix.config }}
          path: ./test-e2e/output/${{ matrix.config }}
          retention-days: 7
